### ISSUE TITLE
兄弟你这个repo使用来干嘛的啊？

### ISSUE THREAD

**Issue by TJRoger** [aiyoheidei/ant_fortune#4]
最近在找蚂蚁财富的数据接口，偶然看到你这个repo，能介绍下这个repo的功能吗？

**Comment by aiyoheidei** [comment]
主要是爬取基金和股票数据，基金包括基金的基本信息、历史记录，股票包括股票的基本信息，还有做基金股票的关联。
        还有一些其他的功能注释里多多少少都写了，最近在找学校调剂，很久没更新了，你可以在此基础上优化一下使用。

**Comment by TJRoger** [comment]
收到，祝你调剂成功：）
